export const SESSION_NAME_MAX_LENGTH = 120;
export const SESSION_DESCRIPTION_MAX_LENGTH = 10000;
export const SESSION_MIN_START_LEAD_MINUTES = 60;
export const SESSION_DRAFT_OPEN_LEAD_MINUTES = 60;
export const SESSION_EDIT_LOCK_LEAD_MINUTES = 15;
