export {
	AVATAR_INPUT_MAX_BYTES,
	AVATAR_INPUT_MAX_MB,
	AVATAR_MAX_BYTES,
	AVATAR_MAX_KB,
	AVATAR_OUTPUT_FILENAME,
	AVATAR_OUTPUT_SIZE,
	AVATAR_OUTPUT_TYPE,
	validateAvatarFile,
	validateAvatarInput
} from '$lib/images/cropAvatar';
